# -*- coding: utf-8 -*-
"""Online API with FastAPI (Corrected Logic)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h2-PmcDlzNy4HtRxUh0GAG8IkRPsyfzD
"""

# main.py
# To run this code:
# 1. Install the necessary libraries:
#    pip install fastapi "uvicorn[standard]"
# 2. Save the code as a file named `main.py`.
# 3. Open your terminal or command prompt.
# 4. Navigate to the directory where you saved the file.
# 5. Run the command: uvicorn main:app --reload

from fastapi import FastAPI
from pydantic import BaseModel
import logging

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = a=logging.getLogger(__name__)

# --- Pydantic Models for Request and Response ---
class QueryRequest(BaseModel):
    language: str
    text: str

class SchemeResponse(BaseModel):
    name: str
    description: str
    eligibility: str
    link: str

# --- Initialize FastAPI App ---
app = FastAPI(
    title="VoiceAI Bharat API",
    description="API for providing information about government schemes.",
    version="1.0.0",
)

# --- Dummy Database with More Schemes ---
DUMMY_SCHEMES_DB = {
    "kisan samman nidhi": {
        "name": "Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)",
        "description": "A government scheme in which all small and marginal farmers will get up to ₹6,000 per year as minimum income support.",
        "eligibility": "All landholding farmer families.",
        "link": "https://pmkisan.gov.in/"
    },
    "beti bachao beti padhao": {
        "name": "Beti Bachao, Beti Padhao",
        "description": "A campaign of the Government of India that aims to generate awareness and improve the efficiency of welfare services intended for girls.",
        "eligibility": "Focused on the girl child.",
        "link": "https://wcd.nic.in/bbbp-schemes"
    },
    "jan dhan yojana": {
        "name": "Pradhan Mantri Jan Dhan Yojana (PMJDY)",
        "description": "National Mission for Financial Inclusion to ensure access to financial services, namely, Banking/ Savings & Deposit Accounts, Remittance, Credit, Insurance, Pension in an affordable manner.",
        "eligibility": "Any Indian citizen above the age of 10 years.",
        "link": "https://www.pmjdy.gov.in/"
    },
    "ujjwala yojana": {
        "name": "Pradhan Mantri Ujjwala Yojana",
        "description": "A scheme of the Ministry of Petroleum & Natural Gas for providing LPG connections to women from Below Poverty Line (BPL) households.",
        "eligibility": "Women belonging to BPL households.",
        "link": "https://www.pmuy.gov.in/"
    },
    "ayushman bharat": {
        "name": "Ayushman Bharat Pradhan Mantri Jan Arogya Yojana (PM-JAY)",
        "description": "A national public health insurance fund of the Government of India that aims to provide free access to health insurance coverage for low income earners in the country.",
        "eligibility": "Poor and vulnerable families based on SECC 2011 data.",
        "link": "https://mera.pmjay.gov.in/search/login"
    },
    "atal pension yojana": {
        "name": "Atal Pension Yojana (APY)",
        "description": "A government-backed pension scheme in India, targeted at the unorganised sector.",
        "eligibility": "Any citizen of India between 18-40 years of age with a bank account.",
        "link": "https://www.npscra.nsdl.co.in/scheme-details.php"
    }
}


# --- API Endpoints ---
@app.get("/")
def read_root():
    """A simple endpoint to check if the API is running."""
    logger.info("Root endpoint was accessed.")
    return {"status": "VoiceAI Bharat API is running!"}

@app.post("/query-schemes", response_model=list[SchemeResponse])
def query_schemes(request: QueryRequest):
    """
    This is the main endpoint for your app.
    It receives a user's query and returns matching schemes.
    """
    logger.info(f"Received query in {request.language}: '{request.text}'")

    query_text = request.text.lower().strip()
    matched_schemes = []

    # *** THIS IS THE CORRECTED LOGIC ***
    # It now checks if the user's query is present in the keyword.
    for keyword, scheme_data in DUMMY_SCHEMES_DB.items():
        if query_text in keyword:
            matched_schemes.append(SchemeResponse(**scheme_data))
            logger.info(f"Matched scheme: {scheme_data['name']}")

    if not matched_schemes:
        logger.warning(f"No schemes found for query: '{query_text}'")

    return matched_schemes